### PR TITLE
Update discovered-app-queries.md

### PR DESCRIPTION
**Pull request by rajesh-k123**

### CODE REVIEW

**Review by dcurwin — APPROVED** [review]

**Comment by dcurwin** [comment]
The PR was approved. When you're ready to publish, please type `#sign-off` in a new comment box, and click **Comment**.

**Comment by Court72** [comment]
@dcurwin

Because this PR was opened in the public repo, only the article's author can sign off. Since you've [approved the changes](https://github.com/MicrosoftDocs/CloudAppSecurityDocs/pull/608#issuecomment-1308636656), we'll go ahead and merge. Thanks!

**Comment by dcurwin** [comment]
@Court72  - Can you please revert this PR? It should not have been published yet.

**Comment by dcurwin** [comment]
> @Court72 - Can you please revert this PR? It should not have been published yet.

Actually, I was able to revert it myself.

**Pull request merged**
