### PR TITLE
added OAuth callout

### PR DESCRIPTION
**Pull request by computeronix**
Wanted to call out OAuth as part of App Permissions under Manage App Permissions for customers looking for this capability
https://docs.microsoft.com/en-us/cloud-app-security/manage-app-permissions

### CODE REVIEW

**Comment by PRMerger13** [comment]
@computeronix : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by shsagir — CHANGES_REQUESTED** [review]
Please change to (OAuth apps)

**Comment by PRMerger17** [comment]
@computeronix : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by computeronix** [comment]
Updated to OAuth apps

**Pull request merged**
