### PR TITLE
Update app-governance-visibility-insights-get-started.md

### PR DESCRIPTION
**Pull request by anandd512**

### CODE REVIEW

**Comment by dcurwin** [comment]
@Court72  - Why was this PR merged? The author did not sign-off yet, and the content isn't ready to go live.

**Comment by Court72** [comment]
Hi @dcurwin,

Note that you're listed as the author in the metadata for *CloudAppSecurityDocs/app-governance-visibility-insights-get-started.md*. Per the [Public PR review process](https://review.docs.microsoft.com/en-us/help/contribute/contribute-vendor-public-prs?branch=main), a PR is ready to merge after the author or another trusted source signs off, approves the changes, or requests merge via the techdocprs alias.

If these changes need to be reverted, please do so in another PR.

Thanks!

**Comment by dcurwin** [comment]
@Court72  - I don't see anything in the article you linked to that indicates that if I approved, the author doesn't need to sign off. Where do you see that?

**Comment by anandd512** [comment]
Hi @dcurwin and @Court72,

I thought the tag 'do-not-merge' was sufficient to ensure that this PR is not merged.
Can you please help revert if it has been merged?
Also, please let me know if there's any change I need to do to ensure this does not happen again -

If I need to be making changes to the private repo - can you please add me to that repo?
If there's any other label that I should add to call out that the PR is not ready to get published?

**Pull request merged**
