### PR TITLE
required role and updated token gen steps

### PR DESCRIPTION
**Pull request by mbegan**
I see no reason for the API token generated to have anything beyond Read-Only Admin rights in Okta

These token generation steps are dated, link to the token generation steps maintained by Okta

### CODE REVIEW

**Comment by PRMerger15** [comment]
@mbegan : Thanks for your contribution! The author, @rkarlin, has been notified to review your proposed change.

**Comment by rkarlin** [comment]
Hi Matt,
thanks for reaching out and taking the time to update the article!
as of now, our Dev team is still working on re-verifying this procedure, and I can't update it until they've verified whether all functionality will continue working with only Read permissions. 
I'll update it if we get the go ahead. 
Thanks,
Rachel

**Comment by mbegan** [comment]
Hi Rachel,

Happy to help and i totally understand.

If they find that something breaks in the process i'd like to learn a little more.

**Comment by rkarlin** [comment]
@msmbaldwin Please close this PR.

**Comment by rkarlin** [comment]
@mbegan I'll let you know when I hear something!

**Comment by ktoliver** [comment]
Closing per @rkarlin

**Pull request closed without merging**
