### PR TITLE
Update app-governance-app-policies-get-started.md

### PR DESCRIPTION
**Pull request by AndrewVahidnia**

### CODE REVIEW

**Comment by PRMerger16** [comment]
@AndrewVahidnia : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ShannonLeavitt** [comment]
@dcurwin – Can you review the proposed changes? IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"

**Review by dcurwin — APPROVED** [review]

**Comment by AndrewVahidnia** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@AndrewVahidnia: I'm sorry - only the author of this article, @dcurwin, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
