### PR TITLE
Update tutorial-suspicious-activity.md

### PR DESCRIPTION
**Pull request by kremertal**

### CODE REVIEW

**Comment by dcurwin** [comment]
Learn Build status updates of commit _[1c71d89](https://github.com/kremertal/CloudAppSecurityDocs/commits/1c71d8958e0ebe173826eeb960383341191cd6d3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[CloudAppSecurityDocs/tutorial-suspicious-activity.md](https://github.com/kremertal/CloudAppSecurityDocs/blob/patch-4/CloudAppSecurityDocs/tutorial-suspicious-activity.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/daf9759b-aa27-219c-4b5e-53f1b72a2d34/202210271030578937-603/BuildReport?accessString=7e899496f52729333d14975707f198e240b5595e6e4fe0f1e7966634e4a17409).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/daf9759b-aa27-219c-4b5e-53f1b72a2d34?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Review by dcurwin — APPROVED** [review]

**Comment by dcurwin** [comment]
The PR was approved. When you're ready to publish, please type `#sign-off` in a new comment box, and click **Comment**.

**Comment by kremertal** [comment]
Great

**Comment by dcurwin** [comment]
> Great

Does that mean you're ready to publish?

**Comment by dcurwin** [comment]
Then please type `#sign-off` in a new comment box and click **Comment**.

**Comment by kremertal** [comment]
#420

**Pull request merged**
