### PR TITLE
Updating 'Test API' string to 'Test Now'

### PR DESCRIPTION
**Pull request by NagarajVenkatesh**

### CODE REVIEW

**Comment by NagarajVenkatesh** [comment]
#sign-off

**Comment by dcurwin** [comment]
Learn Build status updates of commit _[95cb09f](https://github.com/NagarajVenkatesh/CloudAppSecurityDocs/commits/95cb09ff182a9a6bcf92d005c168433ac1facb82)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[CloudAppSecurityDocs/connect-salesforce.md](https://github.com/NagarajVenkatesh/CloudAppSecurityDocs/blob/patch-1/CloudAppSecurityDocs/connect-salesforce.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/daf9759b-aa27-219c-4b5e-53f1b72a2d34/202210201612371581-601/BuildReport?accessString=e693fb474c9afbc280c00c3deab881302e9268f9d9253360e5f6b1122c7bfb44).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/daf9759b-aa27-219c-4b5e-53f1b72a2d34?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by NagarajVenkatesh** [comment]
#sign-off

**Comment by jborsecnik** [comment]
@dcurwin, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Pull request merged**
