### PR TITLE
Salesforce setup instructions using permission sets

### PR DESCRIPTION
**Pull request by Clint-Chester**
This is in reference to #246. I've also updated the screenshots to include the new user interface that's being used by Salesforce.

The current instructions of using profiles are a very heavy handed way to deliver the authentication requirements for the service account. Profiles are designed to give an entire security profile (e.g. app features, database permissions, code access etc.) in the overall security model. So what would be happening at the moment is that when people are following these instructions, they are now needing to manage permissions across all the database permissions and code access areas as well for this new profile that is just used by a service account. This creates an admin overhead for these people and slows down their deployment and testing times.

Permission sets are designed to give additional extensions on top of a base profile. The privileges that CAS needs can all be delivered through permission sets. This will be have considerably less impact on people’s Salesforce instances security models for CAS customers and give them additional flexibility on which service account they'd like to use.

Any feedback or questions please feel free to ask 😄

### CODE REVIEW

**Comment by PRMerger7** [comment]
@Clint-Chester : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@shsagir - Could you review the proposed update to your article?

Thank you.

**Comment by shsagir** [comment]
@Clint-Chester Thanks for the proposed content update. I will review and discuss the changes with the product team and get back to you. Depending on the complexity, it could take from a few business days to a few weeks to look further into your suggestion. I'll contact you if we need further information, and you'll receive an email message each time I "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@Clint-Chester Thanks once again for the feedback. The latest information I have from the product team is that this request was added to our pool of future enhancements. The documentation will be updated once the testing is complete, but it may take a while.

**Comment by Clint-Chester** [comment]
@shsagir thanks for the update 😄

**Comment by shsagir** [comment]
@Clint-Chester  It looks like this may take a while until your suggestions are researched and corresponding topic updates are implemented. Therefore, we're there closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.

**Comment by Clint-Chester** [comment]
> @Clint-Chester It looks like this may take a while until your suggestions are researched and corresponding topic updates are implemented. Therefore, we're there closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.

So both the issue and pull request get closed then? Were there some sort of internal metrics tracking around this (like what is the harm in leaving an open pull request)? To say it's "open" but close everything off really doesn't promote that Open Source transparency. It's pretty disappointing to see that this current advice will continue to be given to your customers using Salesforce 😢. Just disappointed that I went to the effort of showing what the change would be to have it closed off like this.

**Pull request closed without merging**
