### PR TITLE
Added gov dns domains and separated to gov customers and private customers

### PR DESCRIPTION
**Pull request by ilyaMiropolsky**

### CODE REVIEW

**Comment by PRMerger12** [comment]
@ilyaMiropolsky : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @shsagir - Would you review the proposed revisions? 

Thanks.

**Comment by ilyaMiropolsky** [comment]
@shsagir this blocks an important announcement that Alex Esibov wants to dispatch to customers. could you update on the ETA?

**Comment by shsagir** [comment]
Modified in separate PR

**Pull request closed without merging**
