### PR TITLE
Update proxy-intro-aad.md

### PR DESCRIPTION
**Pull request by AmitMishaeli**

### CODE REVIEW

**Review by batamig — APPROVED** [review]
The PR was approved. When you're ready to publish, please type `#sign-off` in a new comment box, and click **Comment**.

**Comment by AmitMishaeli** [comment]
#sign-off

**Comment by AmitMishaeli** [comment]
#sign-off

**Comment by AmitMishaeli** [comment]
#sign-off

**Comment by Court72** [comment]
@batamig

Thanks for approving the PR. Note that in the public repos, PRMerger requires the article's author to sign off.

**Pull request merged**
