### PR TITLE
Update icap-stunnel.md

### PR DESCRIPTION
**Pull request by Kirbogd**
We have recently finished integration of MCAS with Russian DLP solution InfoWatch Traffic Monitor and wanted to provide notes on integration of the DLP solution with MCAS

### CODE REVIEW

**Comment by Kirbogd** [comment]
ISV partner has finished integration and we proposed to update docks to include instructions from their side.

**Comment by GitHubber17** [comment]
@rkarlin - Would you review the proposed changes and add a comment indicating how to proceed:
- `#sign-off` to merge the changes
- `#please-close` to close the request

Thanks

**Comment by PRMerger20** [comment]
@GitHubber17: I'm sorry - only the author of this article, @rkarlin, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by rkarlin** [comment]
@Kirbogd Hi, I'm sorry I didn't look at this sooner - I was on vacation for the last week and a half. I will review your suggested changes with the product team and get back to you. Thanks for your contribution!

**Comment by Kirbogd** [comment]
Thank you Karlin.
There are a few things specific to InfoWatch, but we have recently finished onboarding them into Office 365 DLP story getting one of the major local DLP players into the cloud story. So it would be great to have their specific listed in docs from marketing point of view

With best regards,

Kirill Bogdanov

________________________________
От: rkarlin <notifications@github.com>
Отправлено: воскресенье, июля 15, 2018 3:56 ПП
Кому: MicrosoftDocs/CloudAppSecurityDocs
Копия: Kirbogd; Mention
Тема: Re: [MicrosoftDocs/CloudAppSecurityDocs] Update icap-stunnel.md (#37)


@Kirbogd<https://github.com/Kirbogd> Hi, I'm sorry I didn't look at this sooner - I was on vacation for the last week and a half. I will review your suggested changes with the product team and get back to you. Thanks for your contribution!

**Comment by rkarlin** [comment]
@Kirbogd Thanks again for your update! we don't include instructions for each third-party DLP at this time, but we'll save your information for the future in the event that someone else is interested in using InfoWatch with MCAS.

**Comment by rkarlin** [comment]
#please-close

**Comment by Kirbogd** [comment]
Do we have any plans to have an integration docs library, just like we do for Azure AD with 3rd parties and Azure MFA with 3rd party vpn solutions? May be just referencing online documentation of our partners? For RUssia and CIS InfoWatch and Solar Security are much more relevant then Symantec or Forcepoint and help us to close gap in our DLP solution working with Cyrillic languages.

With best regards,

Kirill Bogdanov

________________________________
От: rkarlin <notifications@github.com>
Отправлено: воскресенье, июля 15, 2018 4:01 ПП
Кому: MicrosoftDocs/CloudAppSecurityDocs
Копия: Kirbogd; Mention
Тема: Re: [MicrosoftDocs/CloudAppSecurityDocs] Update icap-stunnel.md (#37)


@Kirbogd<https://github.com/Kirbogd> Thanks again for your update! we don't include instructions for each third-party DLP at this time, but we'll save your information for the future in the event that someone else is interested in using InfoWatch with MCAS.

**Comment by rkarlin** [comment]
@Kirbogd 
Hi Kirill, thanks for the idea. we don't have any plans for an integration library right now, but thanks a lot for the idea we'll consider it.
Also, feel free to reach out to me with MCAS doc requests and feedback at rkarlin@microsoft.com 
thanks!

**Pull request closed without merging**
