### PR TITLE
Update cas-compliance-trust.md

### PR DESCRIPTION
**Pull request by AmitMishaeli**

### CODE REVIEW

**Comment by Jak-MS** [comment]
@batamig 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by AmitMishaeli** [comment]
#sign-off

**Comment by batamig** [comment]
@AmitMishaeli it looks like you opened this in the public repo instead of the private repo. Please open this in the private repo so that you can sign off. (review.learn.microsoft.com..)

**Comment by AmitMishaeli** [comment]
I've created a new PR (in review.learn) but I cannot sign it off 🙁
PR: #4123

________________________________

**Comment by batamig** [comment]
covered by https://github.com/MicrosoftDocs/CloudAppSecurityDocs-pr/pull/4123.
closing
#please-close

**Pull request closed without merging**
