### PR TITLE
Update set-up-cloud-discovery.md

### PR DESCRIPTION
**Pull request by SLeuthold**
Updated SonicWall name as they are no longer owned by Dell.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@SLeuthold : Thanks for your contribution! The author, @rkarlin, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
The documentation has been updated and the file no longer exists.

**Comment by rkarlin** [comment]
See PR #850

**Comment by ktoliver** [comment]
The proposed changes have been applied in a separate PR. We'll close this pull request.

**Pull request closed without merging**
